POST http://127.0.0.1:8000/api/v1/bookmarks/1
Content-Type: application/json
Authorization: Bearer test

###

DELETE http://127.0.0.1:8000/api/v1/bookmarks/1
Content-Type: application/json
Authorization: Bearer test

###

GET http://127.0.0.1:8000/api/v1/bookmarks
Content-Type: application/json
Authorization: Bearer test

### create like
POST http://127.0.0.1:8000/api/v1/like/1
Content-Type: application/json
Authorization: Bearer test

{
  "rating": 10
}

### get list likes
GET http://127.0.0.1:8000/api/v1/like
Content-Type: application/json
Authorization: Bearer test

### get like
GET http://127.0.0.1:8000/api/v1/like/1
Content-Type: application/json
Authorization: Bearer test

### get likes count
GET http://127.0.0.1:8000/api/v1/like-count/1
Content-Type: application/json
Authorization: Bearer test

### delete like
DELETE http://127.0.0.1:8000/api/v1/like/1
Content-Type: application/json
Authorization: Bearer test

###


