FROM python:3.9

ENV HOME=/code

RUN pip install --upgrade pip
RUN addgroup web && adduser web --home $HOME --ingroup web

WORKDIR $HOME

COPY ./tests/ .
RUN pip install -r requirements.txt

COPY ./entrypoint_tests.sh /usr/local/bin

USER web
