name: CI

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7" ,"3.8", "3.9", ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .ugc-service/requirements.txt
      - name: flake8
        run: |
          flake8 ./ugs-service

      - name: mypy
        run: | 
          mypy ugc-service/ugc-api/src
