name: CI

on:
  push:
    branches: [ master, ci-cd ]
  pull_request:
    branches: [ master ]


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7" ,"3.8", "3.9", ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ugc-service/ugc-api/requirements.txt
      - name: flake8
        run: |
          flake8 ./ugc-service/ugc-api --format=html --htmldir=flake-report
      - name: Archive html lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-result
          path: flake-report

      - name: mypy
        run: |
          mypy ./ugc-service/ugc-api/src
#
#  notify:
#    steps:
#      - name: Notification in telegram
#        run: |
#          curl -i -X GET "https://api.telegram.org/bot${{ secrets.tg_bot_token }}/sendMessage?chat_id=${{ secrets.tg_chat_id }}&text=Pipeline finished"