name: CI

on:
  push:
    branches: [ main, ci-cd ]
  pull_request:
    branches: [ main ]


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7" ,"3.8", "3.9", ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ugc-service/ugc-api/requirements.txt
      - name: flake8
        run: |
          flake8 ./ugc-service/ugc-api --format=html --htmldir=flake-report
      - name: Archive html lint results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: lint-result
          path: flake-report

      - name: mypy
        run: |
          mypy ./ugc-service/ugc-api/src

  notify:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Notification in telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ✅ Pipeline finished with success
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
